modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ccgamepads"
version="1.0.0-neoforge-1.21.1"
displayName="CC: Gamepads"
authors="Tom"
description='''A CC:Tweaked gamepad peripheral with bindable handheld "gamepad items""".'''

[[dependencies.ccgamepads]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.ccgamepads]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.ccgamepads]]
modId="computercraft"
type="required"
versionRange="[1.117.1,)"
ordering="AFTER"
side="BOTH"
